import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Dashboard</h1>
      <Link href="/login">
        <a>Login</a>
      </Link>
      <br />
      <Link href="/dashboard">
        <a>Dashboard</a>
      </Link>
      <br />
      <Link href="/control-panel">
        <a>Control Panel</a>
      </Link>
      <br />
    </>
  )
}

export default Dashboard
