import Head from 'next/head'
import { NextPage } from 'next'
import { useCallback } from 'react'
import { auth } from '@fire/app'

const Login: NextPage = () => {
  const signInWithGoogle = useCallback(async () => {
    try {
      await auth().signInWithPopup(new auth.GoogleAuthProvider())
    } catch (error) {
      console.error(error)
    }
  }, [])

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Login</h1>
      <button onClick={signInWithGoogle}>Sign in with Google</button>
    </>
  )
}

export default Login
